name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: enzo-gabriel-dev
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=#00BFFF&color_dots=#001f3f,#003366,#004080,#0059b3,#0073e6

      - name: push to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
